### ISSUE TITLE
Erro after installing pt-PT.xpi

### ISSUE THREAD

**Issue by smarquespt** [InternalError503/cyberfox-languagepacks#22]
After installing language pack for 50.1 release I´m getting the error attached
![snapshot](https://cloud.githubusercontent.com/assets/1302668/21139603/9a6eac2a-c12b-11e6-8ef5-44b1396d0e49.jpg)

**Comment by smarquespt** [comment]
In English this is something like:

Error parsing XML: error parsing reference to external entity
Location: 
Line number 20, column 1

**Comment by InternalError503** [comment]
Hi @smarquespt hold down the shift key and double click cyberfox shortcut this will trigger a prompt to open in safe-mode, Once in safe-mode remove the old pt-PT pack.

Now re-download the updated pack, There was a small typo that slipped through nothing to major sorry for any inconveniences caused, Thanks for reporting the issue too.

**Comment by smarquespt** [comment]
Thanks for the fix.
