### ISSUE TITLE
[ERROR] Polish langpack: undefined entity

### ISSUE THREAD

**Issue by mati865** [InternalError503/cyberfox-languagepacks#26]
![cyberfox](https://cloud.githubusercontent.com/assets/1174646/22242525/f2afbbcc-e223-11e6-8cfb-a4a7f0894d0c.png)

Translation:
```
XML Parsing Error: undefined entity
Location:chrome://browser/content/browser.xul
Line Number 415, Column 6:
            <menuitem id="context_CloneCurrentTabNewWindowpb">
____________^
```

**Comment by InternalError503** [comment]
Hi @mati865 

Very sorry about this, please reinstall the latest language pack as its been updated.
To remove the current see the [following](https://8pecxstudios.com/Forums/viewtopic.php?f=8&t=210#fourth-solution) then install language pack again from cyberfox website
