### ISSUE TITLE
Japanese langpack: XML parsing error

### ISSUE THREAD

**Issue by dksher** [InternalError503/cyberfox-languagepacks#29]
![langpack](https://cloud.githubusercontent.com/assets/813832/22277208/15c0a160-e2fd-11e6-9dc4-d372edfbaa59.jpg)

With the latest Japanese langpack, XML parsing error happens at startup.

**Comment by InternalError503** [comment]
Hi @dksher 

Please reinstall the latest Japanese language pack as this was fixed early yesterday.
To remove the current see the [following](https://8pecxstudios.com/Forums/viewtopic.php?f=8&t=210#fourth-solution) then install language pack again from cyberfox website
